site_name: FoodMobile App
repo_url: https://github.com/ShahNafisRafique/csc490

nav:
    - Home: index.md
    - User documentation: 
        - Overview: user_docs/overview.md
        - How to Login: user_docs/login.md
        - Navigation: user_docs/navigation.md
        - Managing Favorites: user_docs/favorites.md
        - Managing Dietary/Allergy Information: user_docs/manage_food_settings.md
        - Manage Settings: user_docs/settings.md
    - For Truck Drivers:
        - Register as a Driver and Create a Truck: user_docs/driver_reg.md
    - Project Proposal: project_proposal.md
    - Project Links: repos.md
    - Reports:
        - Combined Report: reports/mega_report.md
    # - Rest:
    #     - API: rest_api.md
    #     - Interface: rest_interface.md
    #     - User: api/user.md

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'images/logo.svg' # https://www.flaticon.com/free-icon/restaurant_685352?term=food&page=1&position=8
    #icon: school #shopping_cart
  font:
    text: 'Roboto'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'orange'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'    
  
# plugins:
#     - search
#     - git-revision-date

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.snippets
  - codehilite:
      linenums: true
      guess_lang: False
      use_pygments: True
      #noclasses: True
      pygments_style: monokai
      
           
extra_css:
  # - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
